name: Rust Build and Release

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Rust Cache
        uses: swatinem/rust-cache@v2

      - name: Install cargo-binstall
        run: cargo install cargo-binstall

      - name: Install Trunk
        run: cargo binstall trunk -y

      - name: Install Tauri CLI
        run: cargo binstall tauri-cli -y

      - name: Build Tauri App
        run: cargo tauri build

      - name: Run backend tests
        run: cargo test -p hazel --verbose
